alias vim="nvim"
alias ll="ls -al"
alias die="wsl.exe --shutdown"
alias autoremove="sudo pacman -Rcns $(pacman -Qdtq)"
alias exp="explorer.exe ."
alias oc="oc.exe"
alias G="git.exe"
alias podman="podman.exe"
